##################################################

# Run Mr Coxall's Super Linter against code base #

##################################################

---

name: Nic's really cool linter

on: [push, pull_request]

jobs:

  run-linters:

    name: Mr Coxall's Super Linter

    runs-on: ubuntu-latest

    steps:

      - name: Check out Git repository

        uses: actions/checkout@main

      - name: Run GitHub Super Linter

        uses: github/super-linter@v4.10.1

        env:

          VALIDATE_ALL_CODEBASE: true

          LINTER_RULES_PATH: /
